### ISSUE TITLE
Example give NULL results

### ISSUE THREAD

**Issue by pboesu** [ropenscilabs/spplit#16]
In the example on https://discuss.ropensci.org/t/feedback-on-pkg-for-connecting-biodiversity-data-and-literature/383 the `sp_bhl_meta` call returns an empty list:

``` r
geom <- 'POLYGON((-124.07 41.48,-119.99 41.48,-119.99 35.57,-124.07 35.57,-124.07 41.48))'
x <- sp_occ_idigbio(geometry = geom, limit = 3)
x <- sp_list(x)
x <- sp_bhl_meta(x)[1:3]
str(x)
List of 3
 $ : NULL
 $ : NULL
 $ : NULL
```

Is the API failing silently?

**Comment by sckott** [comment]
Sorry about that, you need an API key for BHL - updated the discussion forum text https://discuss.ropensci.org/t/feedback-on-pkg-for-connecting-biodiversity-data-and-literature/383 

get an API key from BHL first http://www.biodiversitylibrary.org/getapikey.aspx

**Comment by sckott** [comment]
Okay, reinstall `devtools::install_github("ropenscilabs/spplit")` and try again, should error correctly if you don't have a key, or work if you do have a key

**Comment by pboesu** [comment]
brilliant. thanks!
I updated the help file accordingly and put in a pull request.
